mobile-friendlyなスタイルを適用するオプションを追加
mkizka/MTDeck pull request #13
Opened 2021-05-29 02:11 UTC by mayo0828

本家を参考に少しスマホ向けにスタイル調整されるconfigを追加しました。
mobile-friendly設定はデフォルトONで良いかな、と判断しました。

2021-05-29 10:34 UTC, mkizka requested changes

2021-05-29 10:34 UTC, mkizka commented on src/_locales/ja/messages.json
> +    "message": "スマホ向けのスタイルを適用"
MTDeck自体スマホ向けのスタイルを適用するものなので、全体のスタイルを制御するような感じがあり違う名称が良いと思います。
追加して頂いたスタイルは主にカラム内のスタイルのようなので「カラム内にスマホ向けのスタイルを適用」などが良いと思います。さらに良いものがあれば提案ください。

2021-05-29 10:34 UTC, mkizka commented on src/scss/config.scss
> +}
スタイルの適当なまとまりごとに意図をコメントで書いて欲しいです。
https://github.com/mkizka/MTDeck/blob/f294f2efee1af21aab82b069533ba35f5d8b99a7/src/scss/deck.scss#L37-L59 
こんな感じで簡単なものでよいので、お願いします。

2021-05-29 10:36 UTC, mkizka commented
全体的にかなり良さそうでした！ありがとうございます
2点だけコメントしたので確認お願いします

2021-05-29 13:19 UTC, mayo0828 commented on src/_locales/ja/messages.json
> +    "message": "スマホ向けのスタイルを適用"
@mkizka 
おっしゃる通り、スマホ向けスタイルだと広義すぎるというか今後のことを考えると避けたいですよね。
「カラムにTwitterApp風のスタイルを適用」とかどうでしょうか🤔（風だからセーフ的な）

2021-05-29 13:20 UTC, mayo0828 commented on src/scss/config.scss
> +}
@mkizka 
対応しました🙆‍♀️　[`7245520` (#13)](https://github.com/mkizka/MTDeck/pull/13/commits/72455202ef3f2b2ea77b74d15c690678031b2265)

2021-05-29 15:13 UTC, mkizka commented on src/scss/config.scss
> +}
ありがとうございます！確認しました

2021-05-29 15:39 UTC, mkizka commented on src/_locales/ja/messages.json
> +    "message": "スマホ向けのスタイルを適用"
提案ありがとうございます。考えましたが「カラム内にスマホ向けのスタイルを適用」の方で行こうと思います。TwitterAppに寄せるというより、スマホで使いやすくするための設定としたいと思いました。

あと、カラム外の変更は`.js-int-scroller`のみのようなので、こちらは`menu.scss`のすでにある`.js-int-scroller`に移動させてください。以上よろしくお願いします！

2021-05-29 16:00 UTC, mayo0828 commented on src/_locales/ja/messages.json
> +    "message": "スマホ向けのスタイルを適用"
両方対応しました👍　よろしくお願いします🙏

2021-05-30 04:45 UTC, mkizka commented on src/_locales/ja/messages.json
> +    "message": "スマホ向けのスタイルを適用"
ありがとうございます！

2021-05-30 04:47 UTC, mkizka requested changes

2021-05-30 04:47 UTC, mkizka commented on src/ts/deck.ts
> +    }
ここも`configOptionMobileFriendlyOnCol`だと思います！それ以外は良さそうだと思いました

2021-05-30 11:07 UTC, mayo0828 commented on src/ts/deck.ts
> +    }
対応しました！nameの方は略表現なのかな？と理解したので`mtdMobileStyleFriendly`にしてみました。
https://github.com/mkizka/MTDeck/pull/13/commits/3f47d49c5eb3611f45eba384670de0011ce05067

2021-05-30 13:29 UTC, mkizka commented on src/ts/deck.ts
> +    }
あーーすみません！たしかにそうでした
変更ありがとうございます！

2021-05-30 13:30 UTC, mkizka approved these changes

2021-05-30 13:30 UTC, mkizka commented
細かい調整など対応してくださり本当にありがとうございました！
頂いたプルリクエスト分はこの後新バージョンとしてリリースしておきます

2021-05-30 13:30 UTC, merged

2021-05-30 14:08 UTC, mayo0828 commented
![エンジニアを褒めるネコ:ありがとうございます](https://raw.githubusercontent.com/fukayatsu/lttm-crx/master/vendor/%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%8B%E3%82%A2%E3%82%92%E8%A4%92%E3%82%81%E3%82%8B%E3%83%8D%E3%82%B3/13_%E3%81%82%E3%82%8A%E3%81%8C%E3%81%A8%E3%81%86%E3%81%94%E3%81%96%E3%81%84%E3%81%BE%E3%81%99.png)